[package]
name = "binchotan-backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenvy = "~0.15"
oauth2 = "~4.2.3"
thiserror = "~1.0.32"
anyhow = "~1.0.60"
url = "~2"
reqwest = { version = "~0.11.11", default-features = false, features = ["rustls-tls"] }
serde_json = "~1.0"
serde = "~1"
tokio = { version = "1", features = ["full"] }
tracing = "~0.1"
tracing-subscriber = "~0.2"
toml = "~0.5.9"
ctrlc = "~3.2.3"
mlua = { version = "~0.8.3", features = ["serialize", "lua54", "vendored"] }
tiny_http = "0.11"
open = "3.0.2"
config = "0.13.2"
sqlx = { version = "0.6", features = ["runtime-tokio-rustls", "postgres", "sqlite"] }
uuid = { version = "1.2.1", features = ["v4", "fast-rng"] }
async-trait = "0.1.59"
